!include($SPLICE_ROOT/cluster/configs/shared/scratchnet.yaml)
infra:
  gkeGateway:
    # required for Cloud Armor to be attached to anything
    proxyForIstioHttp: true
cloudArmor:
  enabled: true
  allRulesPreviewOnly: false
  logging:
    enabled: true
    verboseLogging: true
