# Configurations here will be applied after app.conf, and before any ADDITIONAL_CONFIG env vars
# Please use this file for temporary changes that require quick iterations. Always add a TO-DO
# issue when adding things here and either alert an upstream team to upstream your changes
# or open PRs to upstream yourself.

# TODO(DACH-NY/canton-network-internal#7027) Clean up once upstreamed
canton.sequencers.sequencer {
  sequencer {
    config.consensus-empty-block-creation-timeout = 500.milliseconds
    config.output-fetch-how-many-recipients = 2
    block.throughput-cap.messages {
      confirmation-request.strict = false
      topology.strict = false
    }
  }
}
