// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import * as k8s from '@pulumi/kubernetes';
import * as pulumi from '@pulumi/pulumi';

import { localRateLimitedHeader } from './rateLimitHeaders';

interface Limits {
  maxTokens: number;
  tokensPerFill: number;
  fillInterval: string;
}

export interface PerIpLimits extends Limits {
  overrides?: Record<string, { ips: string[] } & Limits>;
}

interface MatchedLimits extends Limits {
  type: 'limited';
  perIpLimits?: PerIpLimits;
}

interface LocalLimits<L> {
  [pathPrefix: string]: LocalLimit<L>;
}

type LocalLimit<L> = {
  name: string;
} & L;

// The descriptor entry key emitted by envoy's `masked_remote_address` rate limit action.
// This is hardcoded in envoy (see MaskedRemoteAddressAction::populateDescriptor) and
// cannot be configured, so the descriptors we generate must use exactly this key.
const clientIpEntryKey = 'masked_remote_address';
const reservedEntryKeys = [clientIpEntryKey, 'client_ip'];

// The per-IP descriptors are wildcard descriptors: envoy allocates a token bucket per
// observed client IP and keeps them in an LRU cache whose size defaults to a mere 20
// entries.
export const maxDynamicDescriptorsPerLimit = 10000;

// Envoy rejects token buckets refilling faster than this, and requires every descriptor
// fill interval to be a multiple of the global (default) bucket's fill interval.
const minFillIntervalMs = 50;

// uint32 in envoy's TokenBucket proto
const maxTokenValue = 4294967295;

// Within one local rate limit filter, envoy consumes a token from at most *one* descriptor
// bucket per request (the first descriptor matching the descriptors generated by the route's
// rate limit actions), plus a token from the filter's own default token bucket.
// Limits that must all be respected therefore live in separate filters, each of which consumes
// a token of its own bucket for every request. There is exactly one filter per limit, so that
// the metrics and the access logs can attribute a rejection to the limit that caused it:
//   - `perEndpointPerIpRateLimitFilterName`: the per-endpoint, per-client-IP limits (including
//     the per-IP overrides).
//   - `perEndpointRateLimitFilterName`: the per-endpoint limits, one bucket per configured
//     endpoint.
//   - `globalPerIpRateLimitFilterName`: a single wildcard descriptor keyed on the client IP, i.e.
//     one bucket per client IP, consumed by every request.
//   - `globalRateLimitFilterName`: the global limit, consumed by every request.
// The descriptor sets of the filters are disjoint, so they can share the route level rate limit
// actions without interfering with each other.
// The filters run in that order, from the most to the least specific limit, so that a request
// rejected by a specific limit does not consume the tokens of the broader buckets: a client
// hammering a single endpoint burns its own per-endpoint per-IP bucket and leaves the global
// bucket to everybody else.
export const globalRateLimitFilterName = 'envoy.filters.http.local_ratelimit';
export const perEndpointRateLimitFilterName = 'envoy.filters.http.local_ratelimit.endpoint';
export const globalPerIpRateLimitFilterName = 'envoy.filters.http.local_ratelimit.per_ip';
export const perEndpointPerIpRateLimitFilterName =
  'envoy.filters.http.local_ratelimit.endpoint_per_ip';

// Envoy emits `<stat_prefix>.http_local_rate_limit.{enabled,ok,rate_limited,enforced}` per filter
// and does not label them, so the stat prefix is the only thing telling the filters apart in the
// metrics. Every filter therefore uses `<rateLimiterStatPrefix>_<limiter>` as its stat prefix, and
// prometheus rewrites the scraped series into a single metric name carrying the limiter in a
// label (see `rateLimiterMetricRelabelings`):
//   envoy_http_local_rate_limiter_per_ip_http_local_rate_limit_enforced
//     -> envoy_http_local_rate_limit_enforced{limiter="per_ip"}
export const rateLimiterStatPrefix = 'http_local_rate_limiter';
// the metric name all the limiters share after relabeling
export const rateLimiterMetricPrefix = 'envoy_http_local_rate_limit';
// the label the limiter ends up in after relabeling
export const rateLimiterLabel = 'limiter';

// The name of each limit, used both as the value of the `x-local-rate-limit` response header (which
// identifies the limit that rejected a request in the sidecar access logs, as the metrics cannot
// attribute a single request to a limit) and as the value of the `limiter` metric label.
export const globalRateLimitName = 'global';
export const perEndpointRateLimitName = 'endpoint';
export const globalPerIpRateLimitName = 'per_ip';
export const perEndpointPerIpRateLimitName = 'endpoint_per_ip';

export const globalRateLimitStatPrefix = `${rateLimiterStatPrefix}_${globalRateLimitName}`;
export const perEndpointRateLimitStatPrefix = `${rateLimiterStatPrefix}_${perEndpointRateLimitName}`;
export const globalPerIpRateLimitStatPrefix = `${rateLimiterStatPrefix}_${globalPerIpRateLimitName}`;
export const perEndpointPerIpRateLimitStatPrefix = `${rateLimiterStatPrefix}_${perEndpointPerIpRateLimitName}`;

/**
 * The prometheus `metric_relabel_configs` turning the per-filter metric names into a single metric
 * name labeled by limiter.
 */
export const rateLimiterMetricRelabelings = [
  {
    // extract the limiter from the metric name, must run before the name is rewritten
    sourceLabels: ['__name__'],
    regex: `envoy_${rateLimiterStatPrefix}_(.+)_http_local_rate_limit_.+`,
    targetLabel: rateLimiterLabel,
    replacement: '$1',
    action: 'replace',
  },
  {
    // and normalize the metric name, so that all the limiters share it
    sourceLabels: ['__name__'],
    regex: `envoy_${rateLimiterStatPrefix}_.+_http_local_rate_limit_(.+)`,
    targetLabel: '__name__',
    replacement: `${rateLimiterMetricPrefix}_$1`,
    action: 'replace',
  },
];

export interface RateLimitEnvoyFilterArgs extends PerEndpointLimits {
  namespace: string;

  appLabel: pulumi.Input<string>;

  inboundPort: pulumi.Input<number>;

  // consumed by every request
  globalLimits: Limits;

  // consumed by every request, keyed on the client IP, with optional per-IP overrides
  globalPerIpLimits: PerIpLimits;

  // the protocol spoken on the rate limited port, `http` by default
  protocol?: RateLimitProtocol;
}

// The protocol the rate limited workload speaks. It determines how the configured path prefixes are
// validated, and how envoy reports a rejection: an HTTP request rejected by the local rate limit
// filter gets `429`, whereas a gRPC call gets HTTP `200` and a gRPC status in the response, so the
// two are recognized differently in the metrics and the access logs.
export type RateLimitProtocol = 'http' | 'grpc';

// The gRPC status code (`RESOURCE_EXHAUSTED`) envoy returns for a rate limited gRPC call, see
// `rate_limited_as_resource_exhausted` in `localRateLimitFilterConfig`.
export const rateLimitedGrpcStatus = 8;

export interface PerEndpointLimits {
  // all the rate limits must be respected, there's an AND relationship between them
  rateLimits?: LocalLimits<MatchedLimits>;
}

export function extractPathPrefixes(rateLimits?: PerEndpointLimits['rateLimits']): string[] {
  if (!rateLimits) {
    return [];
  }

  return Object.keys(rateLimits).filter(
    pathPrefix => pathPrefix.startsWith('/api/scan') || pathPrefix.startsWith('/registry')
  );
}

/**
 * Checks that the configured path prefixes can actually match a gRPC request.
 *
 * gRPC maps every call onto the HTTP/2 path `/<fully.qualified.Service>/<Method>`, which is what
 * the route level `header_match` actions match on. A prefix that is not of that shape (e.g. an
 * HTTP endpoint such as `/api/scan/v0/...`, or a bare service name without the leading slash)
 * would never match any request, so the limit would silently never be enforced.
 */
export function validateGrpcPathPrefixes(rateLimits?: PerEndpointLimits['rateLimits']): void {
  // `/<service>/` optionally followed by a method name; the service must be a dotted, non-empty
  // fully qualified protobuf name.
  const grpcPathPrefix = /^\/[A-Za-z_][\w]*(\.[A-Za-z_][\w]*)+\/[A-Za-z_]?\w*$/;
  const invalid = Object.keys(rateLimits || {}).filter(
    pathPrefix => !grpcPathPrefix.test(pathPrefix)
  );
  if (invalid.length > 0) {
    throw new Error(
      `invalid gRPC path prefixes: ${invalid.join(', ')}; expected '/<fully.qualified.Service>/<Method>' ` +
        `(a trailing '/' matches every method of the service), otherwise the limit would never match a request`
    );
  }
}

export function validateIpLimits(context: string, perIpLimits?: PerIpLimits): void {
  if (!perIpLimits) {
    return;
  }

  const seenIps = new Set<string>();
  const duplicates: string[] = [];

  Object.entries(perIpLimits.overrides || {}).forEach(([overrideKey, override]) => {
    override.ips.forEach(ip => {
      if (seenIps.has(ip)) {
        duplicates.push(`${ip} (in override '${overrideKey}')`);
      } else {
        seenIps.add(ip);
      }
    });
  });

  if (duplicates.length > 0) {
    throw new Error(`${context}: duplicate IPs in per-IP rate limits: ${duplicates.join(', ')}`);
  }
}

/**
 * Parses a protobuf duration (as accepted by envoy's `fill_interval`) into milliseconds.
 */
export function parseFillIntervalMs(fillInterval: string, context: string): number {
  const match = /^(\d+(?:\.\d+)?)s$/.exec(fillInterval);
  if (!match) {
    throw new Error(
      `${context}: invalid fillInterval '${fillInterval}', expected a duration in seconds such as '60s'`
    );
  }
  return Math.round(parseFloat(match[1]) * 1000);
}

function validateLimits(context: string, limits: Limits, globalFillIntervalMs?: number): void {
  const fillIntervalMs = parseFillIntervalMs(limits.fillInterval, context);
  // envoy rejects fill intervals below 50ms, see the local rate limit filter docs.
  // https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-field-extensions-filters-http-local-ratelimit-v3-localratelimit-token-bucket
  if (fillIntervalMs < minFillIntervalMs) {
    throw new Error(
      `${context}: fillInterval '${limits.fillInterval}' is below the ${minFillIntervalMs}ms minimum enforced by envoy`
    );
  }
  // envoy requires descriptor fill intervals to be a multiple of the default bucket's
  // fill interval; violating this makes istiod push a config that envoy NACKs, which
  // silently leaves the sidecar running without any rate limits at all.
  // https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-field-extensions-filters-http-local-ratelimit-v3-localratelimit-descriptors
  if (globalFillIntervalMs !== undefined && fillIntervalMs % globalFillIntervalMs !== 0) {
    throw new Error(
      `${context}: fillInterval '${limits.fillInterval}' must be a multiple of the globalLimits fillInterval (${globalFillIntervalMs}ms)`
    );
  }
  [['maxTokens', limits.maxTokens] as const, ['tokensPerFill', limits.tokensPerFill] as const]
    .filter(([, value]) => !Number.isInteger(value) || value < 0 || value > maxTokenValue)
    .forEach(([field, value]) => {
      throw new Error(
        `${context}: ${field} must be an integer in [0, ${maxTokenValue}], got ${value}`
      );
    });
}

function validatePerIpTokenBuckets(
  context: string,
  perIpLimits: PerIpLimits,
  globalFillIntervalMs?: number
): void {
  validateLimits(context, perIpLimits, globalFillIntervalMs);
  Object.entries(perIpLimits.overrides || {}).forEach(([name, override]) =>
    validateLimits(`${context} override '${name}'`, override, globalFillIntervalMs)
  );
}

export function validateTokenBuckets(
  globalLimits: Limits,
  effectiveRateLimits: LocalLimits<MatchedLimits>,
  globalPerIpLimits?: PerIpLimits
): void {
  validateLimits('globalLimits', globalLimits);
  const globalFillIntervalMs = parseFillIntervalMs(globalLimits.fillInterval, 'globalLimits');
  if (globalPerIpLimits) {
    validatePerIpTokenBuckets('globalPerIpLimits', globalPerIpLimits, globalFillIntervalMs);
  }
  Object.entries(effectiveRateLimits).forEach(([pathPrefix, rateLimit]) => {
    validateLimits(pathPrefix, rateLimit, globalFillIntervalMs);
    if (rateLimit.perIpLimits) {
      validatePerIpTokenBuckets(
        `${pathPrefix} perIpLimits`,
        rateLimit.perIpLimits,
        globalFillIntervalMs
      );
    }
  });
}

export function validateEffectiveRateLimits(
  args: RateLimitEnvoyFilterArgs
): LocalLimits<MatchedLimits> {
  const collidingPathNames = Object.entries(args.rateLimits || {})
    .filter(([, rl]) => reservedEntryKeys.includes(rl.name))
    .map(([path]) => path);
  if (collidingPathNames.length > 0) {
    throw new Error(
      `${collidingPathNames.join(', ')} use reserved name ${reservedEntryKeys.join('/')}; choose a different name`
    );
  }

  const effectiveRateLimits: LocalLimits<MatchedLimits> = args.rateLimits || {};

  // the name is the descriptor value identifying the endpoint bucket, so two endpoints sharing
  // one would share their buckets (and make envoy reject the duplicated descriptors)
  const names = Object.values(effectiveRateLimits).map(rl => rl.name);
  const duplicateNames = [...new Set(names.filter((name, i) => names.indexOf(name) !== i))];
  if (duplicateNames.length > 0) {
    throw new Error(
      `duplicate rate limit names: ${duplicateNames.join(', ')}; every endpoint needs its own name`
    );
  }

  if (args.protocol === 'grpc') {
    validateGrpcPathPrefixes(effectiveRateLimits);
  }

  validateIpLimits('globalPerIpLimits', args.globalPerIpLimits);
  Object.entries(effectiveRateLimits).forEach(([pathPrefix, rateLimit]) => {
    validateIpLimits(pathPrefix, rateLimit.perIpLimits);
  });

  validateTokenBuckets(args.globalLimits, effectiveRateLimits, args.globalPerIpLimits);

  return effectiveRateLimits;
}

export function clientIpDescriptorValue(ip: string): string {
  return `${ip}/32`;
}

// We deliberately do not key on the raw x-forwarded-for header: clients can
// prepend arbitrary entries to it, and our gateway only appends to it, so
// the header value is attacker controlled and per-IP limits could be evaded
// by simply varying the header on every request.
// masked_remote_address instead uses the address envoy trusts, which for the
// sidecar is the last x-forwarded-for hop, i.e. the one appended by our own
// ingress gateway.
const maskedRemoteAddressAction = {
  masked_remote_address: {
    // one bucket per client address
    v4_prefix_mask_len: 32,
    // the default of 0 would put all IPv6 clients into a single bucket
    v6_prefix_mask_len: 128,
  },
};

export function buildGlobalPerIpRateLimitAction(): unknown {
  return { actions: [maskedRemoteAddressAction] };
}

/**
 * The per-client-IP descriptors for a set of per-IP limits, ordered from the most to the least
 * specific one, as envoy consumes a token from the first matching descriptor only: the IP-specific
 * overrides come first, the wildcard (one bucket per observed client IP) descriptor last.
 * `baseEntries` are the descriptor entries the limits are scoped to, e.g. the per-endpoint
 * `header_match` entry, or none at all for the global per-IP limits.
 */
function buildPerIpDescriptors(
  baseEntries: { key: string; value?: string }[],
  perIpLimits: PerIpLimits
): unknown[] {
  const descriptors: unknown[] = [];

  // IP-specific overrides first, so they take precedence over the generic per-IP bucket
  Object.values(perIpLimits.overrides || {}).forEach(override => {
    override.ips.forEach(ip => {
      descriptors.push({
        entries: [...baseEntries, { key: clientIpEntryKey, value: clientIpDescriptorValue(ip) }],
        token_bucket: tokenBucket(override),
      });
    });
  });

  // Generic per-IP fallback last
  descriptors.push({
    entries: [...baseEntries, { key: clientIpEntryKey }],
    token_bucket: tokenBucket(perIpLimits),
  });

  return descriptors;
}

/**
 * The descriptors of the filter enforcing the global per-client-IP limit: the IP-specific overrides,
 * followed by the wildcard bucket applying to every other client IP.
 */
export function buildGlobalPerIpRateLimitDescriptors(globalPerIpLimits: PerIpLimits): unknown[] {
  return buildPerIpDescriptors([], globalPerIpLimits);
}

function tokenBucket(limits: Limits): unknown {
  return {
    max_tokens: limits.maxTokens,
    tokens_per_fill: limits.tokensPerFill,
    fill_interval: limits.fillInterval,
  };
}

function pathMatcher(pathPrefix: string, invertMatch: boolean): unknown {
  return {
    name: ':path',
    string_match: {
      prefix: pathPrefix,
      ignore_case: true,
    },
    // the matchers of a `header_value_match` action are ANDed, so an inverted one excludes
    // the requests matching that prefix
    ...(invertMatch ? { invert_match: true } : {}),
  };
}

/**
 * The configured path prefixes that are strictly more specific than `pathPrefix`, i.e. whose
 * requests are a subset of the ones matched by `pathPrefix`.
 */
export function moreSpecificPathPrefixes(pathPrefix: string, allPathPrefixes: string[]): string[] {
  return allPathPrefixes.filter(
    other =>
      other.length > pathPrefix.length &&
      // envoy matches the prefixes case insensitively, so the comparison must too
      other.toLowerCase().startsWith(pathPrefix.toLowerCase())
  );
}

export function buildRateLimitActions(effectiveRateLimits: LocalLimits<MatchedLimits>): unknown[] {
  const allPathPrefixes = Object.keys(effectiveRateLimits);
  return Object.entries(effectiveRateLimits).flatMap(([pathPrefix, rateLimit]) => {
    const actions = [];

    // Action 1: generate the per-endpoint action.
    // Configured prefixes may nest (e.g. `/registry/transfer-instruction/v1` and
    // `/registry/transfer-instruction/v1/transfer-factory`). Without excluding the more specific
    // prefixes, a request to the nested endpoint would generate *both* descriptors, and envoy
    // consumes at most one descriptor bucket per filter, which would silently drop the limit
    // configured for the more specific endpoint. Hence every endpoint matches exactly the
    // requests that no more specific endpoint matches.
    const baseAction = {
      header_value_match: {
        descriptor_value: rateLimit.name,
        expect_match: true,
        headers: [
          pathMatcher(pathPrefix, false),
          ...moreSpecificPathPrefixes(pathPrefix, allPathPrefixes).map(nested =>
            pathMatcher(nested, true)
          ),
        ],
      },
    };

    actions.push({ actions: [baseAction] });

    // Action 2: generate the per-IP action if perIpLimits exists
    if (rateLimit.perIpLimits) {
      actions.push({
        actions: [baseAction, maskedRemoteAddressAction],
      });
    }

    return actions;
  });
}

/**
 * The descriptors of the filter enforcing the global limit: one bucket per configured endpoint.
 * The global bucket itself is the filter's default token bucket, which is consumed by every
 * request, including the ones matching one of these descriptors.
 */
export function buildEndpointRateLimitDescriptors(
  effectiveRateLimits: LocalLimits<MatchedLimits>
): unknown[] {
  return Object.values(effectiveRateLimits).map(rateLimit => ({
    entries: [{ key: 'header_match', value: rateLimit.name }],
    token_bucket: tokenBucket(rateLimit),
  }));
}

/**
 * The descriptors of the filter enforcing the per-endpoint, per-client-IP limits, ordered from the
 * most to the least specific one, as envoy consumes a token from the first matching descriptor
 * only. These are consumed on top of the global per-client-IP bucket, which is enforced by a
 * separate filter.
 */
export function buildPerEndpointPerIpRateLimitDescriptors(
  effectiveRateLimits: LocalLimits<MatchedLimits>
): unknown[] {
  return Object.values(effectiveRateLimits).flatMap(rateLimit =>
    rateLimit.perIpLimits
      ? buildPerIpDescriptors(
          [{ key: 'header_match', value: rateLimit.name }],
          rateLimit.perIpLimits
        )
      : []
  );
}

/**
 * A bucket that never rate limits anything, used as the default token bucket of the filters whose
 * limits are all expressed as descriptors. Envoy requires the default bucket to be set, but these
 * filters must not limit requests that match none of their descriptors.
 */
function unlimitedTokenBucket(fillInterval: string): Limits {
  return {
    maxTokens: maxTokenValue,
    tokensPerFill: maxTokenValue,
    fillInterval,
  };
}

/**
 * A local rate limit filter: envoy consumes a token of its default bucket and/or of the first of
 * its descriptors matching the request, independently of the other filters.
 */
export interface RateLimitFilter {
  // the name of the filter in the HTTP filter chain, also the typed_per_filter_config key
  name: string;
  // the prefix of the metrics emitted by this filter
  statPrefix: string;
  // the value of the `x-local-rate-limit` response header set by this filter
  limitName: string;
  defaultTokenBucket: Limits;
  alwaysConsumeDefaultTokenBucket: boolean;
  descriptors: unknown[];
}

function localRateLimitFilterConfig(filter: RateLimitFilter, protocol: RateLimitProtocol): unknown {
  return {
    '@type': 'type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit',
    stat_prefix: filter.statPrefix,
    token_bucket: tokenBucket(filter.defaultTokenBucket),
    // whether the default (non-descriptor) bucket is consumed by requests that matched one
    // of the descriptors below
    always_consume_default_token_bucket: filter.alwaysConsumeDefaultTokenBucket,
    // A rate limited gRPC call is answered with HTTP 200 and a gRPC status; without this envoy
    // reports the generic `UNAVAILABLE` (14), which clients cannot tell apart from a genuinely
    // unavailable server (and typically retry). `RESOURCE_EXHAUSTED` (8) unambiguously identifies
    // a rejection by the rate limiter, both for the client and in the sidecar access logs.
    rate_limited_as_resource_exhausted: protocol === 'grpc',
    filter_enabled: {
      runtime_key: 'local_rate_limit_enabled',
      default_value: {
        numerator: 100,
        denominator: 'HUNDRED',
      },
    },
    filter_enforced: {
      runtime_key: 'local_rate_limit_enforced',
      default_value: {
        numerator: 100,
        denominator: 'HUNDRED',
      },
    },
    response_headers_to_add: [
      {
        append_action: 'OVERWRITE_IF_EXISTS_OR_ADD',
        header: {
          key: localRateLimitedHeader,
          // identifies the limit that rejected the request in the sidecar access logs
          value: filter.limitName,
        },
      },
    ],
    // Emit X-RateLimit-Limit/Remaining/Reset.
    // used in sidecar access logs
    // not sent to the client, because we strip them on the ingress gateway
    enable_x_ratelimit_headers: 'DRAFT_VERSION_03',
    max_dynamic_descriptors: maxDynamicDescriptorsPerLimit,
    // Only the first matching descriptor is used, hence they are ordered from the most to the
    // least specific one. Limits that must apply on top of each other live in separate filters.
    descriptors: filter.descriptors,
  };
}

/**
 * The local rate limit filters to install, one per limit that must be respected on its own, ordered
 * from the most to the least specific limit.
 * Every request consumes a token from the global bucket *and* a token from the bucket of its
 * client IP, and, on the endpoints with configured limits, a token from the per-endpoint bucket
 * and one from the per-endpoint bucket of its client IP.
 * The filters run in the returned order, so a request rejected by a more specific limit never
 * reaches (and never consumes the tokens of) the broader ones.
 */
export function buildRateLimitFilters(
  globalLimits: Limits,
  globalPerIpLimits: PerIpLimits,
  effectiveRateLimits: LocalLimits<MatchedLimits>
): RateLimitFilter[] {
  const perEndpointPerIpDescriptors =
    buildPerEndpointPerIpRateLimitDescriptors(effectiveRateLimits);
  const perEndpointDescriptors = buildEndpointRateLimitDescriptors(effectiveRateLimits);
  // a filter without descriptors would only ever consume its (unlimited) default bucket
  const endpointFilters: RateLimitFilter[] = [
    // consumed on top of the global per-IP bucket, requests to endpoints without per-IP limits
    // match no descriptor here and are not limited by this filter
    ...(perEndpointPerIpDescriptors.length > 0
      ? [
          {
            name: perEndpointPerIpRateLimitFilterName,
            statPrefix: perEndpointPerIpRateLimitStatPrefix,
            limitName: perEndpointPerIpRateLimitName,
            defaultTokenBucket: unlimitedTokenBucket(globalLimits.fillInterval),
            alwaysConsumeDefaultTokenBucket: false,
            descriptors: perEndpointPerIpDescriptors,
          },
        ]
      : []),
    // one bucket per configured endpoint; requests to any other endpoint match no descriptor
    // here and are only limited globally
    ...(perEndpointDescriptors.length > 0
      ? [
          {
            name: perEndpointRateLimitFilterName,
            statPrefix: perEndpointRateLimitStatPrefix,
            limitName: perEndpointRateLimitName,
            defaultTokenBucket: unlimitedTokenBucket(globalLimits.fillInterval),
            alwaysConsumeDefaultTokenBucket: false,
            descriptors: perEndpointDescriptors,
          },
        ]
      : []),
  ];
  return [
    ...endpointFilters,
    {
      name: globalPerIpRateLimitFilterName,
      statPrefix: globalPerIpRateLimitStatPrefix,
      limitName: globalPerIpRateLimitName,
      // every request matches one of the descriptors below, so this bucket is never used
      defaultTokenBucket: unlimitedTokenBucket(globalLimits.fillInterval),
      alwaysConsumeDefaultTokenBucket: false,
      // one bucket per client IP (or per IP-specific override), consumed by every request
      descriptors: buildGlobalPerIpRateLimitDescriptors(globalPerIpLimits),
    },
    {
      name: globalRateLimitFilterName,
      statPrefix: globalRateLimitStatPrefix,
      limitName: globalRateLimitName,
      // the global limit applies to every request, and it is the only limit this filter enforces,
      // so that a rejection is unambiguously attributed to it in the metrics and the access logs
      defaultTokenBucket: globalLimits,
      alwaysConsumeDefaultTokenBucket: true,
      descriptors: [],
    },
  ];
}

/**
 * The per-route configuration of the local rate limit filters, keyed by filter name.
 */
export function buildTypedPerFilterConfig(
  filters: RateLimitFilter[],
  protocol: RateLimitProtocol = 'http'
): Record<string, unknown> {
  return Object.fromEntries(
    filters.map(filter => [filter.name, localRateLimitFilterConfig(filter, protocol)])
  );
}

/**
 * The `HTTP_FILTER` config patches adding the rate limit filters to the sidecar's HTTP filter
 * chain. Each of them consumes a token of its own buckets, so that a single request consumes a
 * global token, a token of the bucket of its client IP, and the per-endpoint tokens where
 * configured.
 * The insertion point is pinned to the router filter, which is always the last filter of the
 * chain: istio applies the patches in order, each of them inserting right before the router, so
 * the filters end up in the chain in the order of `buildRateLimitFilters`, i.e. from the most to
 * the least specific limit. Without the `subFilter` match istio would instead insert every filter
 * before the *first* filter of the chain, silently reversing them.
 * The patches are scoped to `inboundPort`, the port carrying the externally reachable API. A
 * workload typically listens on further ports that are not exposed to the outside (e.g. the
 * sequencer's admin and peer-to-peer ports, which istio also treats as HTTP because they are
 * named `grpc-*`); without the port match the filters would be inserted into the filter chains of
 * those listeners too, and internal traffic must never be rate limited.
 */
export function buildHttpFilterPatches(
  filters: RateLimitFilter[],
  inboundPort: pulumi.Input<number>
): unknown[] {
  return filters.map(filter => ({
    applyTo: 'HTTP_FILTER',
    match: {
      context: 'SIDECAR_INBOUND',
      listener: {
        portNumber: inboundPort,
        filterChain: {
          filter: {
            name: 'envoy.filters.network.http_connection_manager',
            subFilter: {
              name: 'envoy.filters.http.router',
            },
          },
        },
      },
    },
    patch: {
      operation: 'INSERT_BEFORE',
      value: {
        name: filter.name,
        typed_config: {
          '@type': 'type.googleapis.com/udpa.type.v1.TypedStruct',
          type_url:
            'type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit',
          value: {
            // the filters are disabled by default and only enabled (and configured)
            // on the routes via typed_per_filter_config below
            stat_prefix: filter.statPrefix,
          },
        },
      },
    },
  }));
}

export class RateLimitEnvoyFilter extends pulumi.ComponentResource {
  public readonly envoyFilter: k8s.apiextensions.CustomResource;

  constructor(
    name: string,
    args: RateLimitEnvoyFilterArgs,
    opts?: pulumi.ComponentResourceOptions
  ) {
    super('splice:RateLimit', `splice-${args.namespace}-${name}`, args, opts);
    const effectiveRateLimits = validateEffectiveRateLimits(args);

    // The global per-IP action comes last so that the more specific per-endpoint
    // descriptors are matched first.
    const rateLimitActions = buildRateLimitActions(effectiveRateLimits).concat([
      buildGlobalPerIpRateLimitAction(),
    ]);
    const rateLimitFilters = buildRateLimitFilters(
      args.globalLimits,
      args.globalPerIpLimits,
      effectiveRateLimits
    );

    this.envoyFilter = new k8s.apiextensions.CustomResource(
      `${args.namespace}-${name}`,
      {
        apiVersion: 'networking.istio.io/v1alpha3',
        kind: 'EnvoyFilter',
        metadata: {
          name: name,
          namespace: args.namespace,
        },
        spec: {
          workloadSelector: {
            labels: {
              app: args.appLabel,
            },
          },
          configPatches: [
            ...buildHttpFilterPatches(rateLimitFilters, args.inboundPort),
            // Configure the rate limiting rules on the HTTP route.
            {
              applyTo: 'HTTP_ROUTE',
              match: {
                context: 'SIDECAR_INBOUND',
                routeConfiguration: {
                  vhost: {
                    name: pulumi.interpolate`inbound|http|${args.inboundPort}`,
                    route: { action: 'ANY' },
                  },
                },
              },
              patch: {
                operation: 'MERGE',
                value: {
                  route: {
                    // shared by all the filters: the descriptors generated here are matched
                    // against the descriptors of each filter, which are disjoint
                    rate_limits: rateLimitActions,
                  },
                  typed_per_filter_config: buildTypedPerFilterConfig(
                    rateLimitFilters,
                    args.protocol || 'http'
                  ),
                },
              },
            },
          ],
        },
      },
      { parent: this }
    );

    this.registerOutputs({
      envoyFilter: this.envoyFilter,
    });
  }
}
