logging:
  appsLogLevel: DEBUG
  appsAsync: false
  cantonLogLevel: DEBUG
  apiRequestLogLevel: DEBUG
  cantonAsync: false
  cometbftLogLevel: debug
pruning:
  sequencer:
    enabled: false
  participant:
    enabled: true
    cron: '0 /10 * * * ?'
    maxDuration: 5m
    retentionPeriod: 30d
participant:
  bftSequencerConnection: true
  resources:
    requests:
      memory: '12Gi'
    limits:
      memory: '18Gi'
  additionalEnvVars:
    - !include(./participant_pruning.yaml)
validatorApp:
  resources:
    requests:
      memory: '2Gi'
    limits:
      memory: '4Gi'
